global using FreeSql;
global using FreeSql.DataAnnotations;
global using MultiOpenBrowser.Base;
global using MultiOpenBrowser.Base.Generic;
global using MultiOpenBrowser.Entitys;
global using MultiOpenBrowser.Helpers;
global using MultiOpenBrowser.Repositorys;
global using NLog;
global using System.ComponentModel;